apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: wild-bunch-learning
  labels:
    app.kubernetes.io/part-of: wild-bunch-learning
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: wild-bunch-frontend
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: wild-bunch-learning
  labels:
    app.kubernetes.io/part-of: wild-bunch-learning
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: wild-bunch-api
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
