REVOKE CREATE ON DATABASE wildbunch FROM PUBLIC;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT CONNECT ON DATABASE wildbunch TO wildbunch_runtime;
GRANT USAGE ON SCHEMA public TO wildbunch_runtime;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO wildbunch_runtime;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO wildbunch_runtime;
