apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wild-bunch-learning
resources:
  - ../../base
  - config.yaml
  - release-rbac.yaml
replicas:
  - name: api
    count: 1
  - name: frontend
    count: 1
