namespace WildBunch.Domain.Game;

/// <summary>
/// Tracks heat: future lawman pursuit pressure generated by noisy/visible
/// behavior (fights, bribes, confrontations, conspicuous trail incidents).
/// Heat is NOT trail danger, route danger, generic encounter risk, or
/// reputation. A future lawman system will consume heat as a pressure clock;
/// until then no lawman catches the player on the trail. See ADR-0029.
/// </summary>
public sealed class PursuitState
{
    public int Heat { get; private set; }

    public void IncreaseHeat(int amount)
    {
        Heat = Math.Max(0, Heat + amount);
    }

    /// <summary>
    /// Sets heat to an absolute value. Used by event-sourced Apply methods
    /// that carry the absolute heat (e.g. TravelDayAdvanced) so command-path
    /// direct mutations and replay-path event applications converge on the
    /// same state. See ADR-0028 and BUNCH-83.
    /// </summary>
    internal void SetHeat(int value)
    {
        Heat = Math.Max(0, value);
    }
}
