// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WildBunch.Persistence;

#nullable disable

namespace WildBunch.Persistence.Migrations
{
    [DbContext(typeof(WildBunchDbContext))]
    [Migration("20260531081955_ComposedSessionPersistence")]
    partial class ComposedSessionPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("WildBunch.Persistence.GameSessions.GameSessionComponentEntity", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ComponentName")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("ComponentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("SessionId", "ComponentName");

                    b.ToTable("GameSessionComponents", (string)null);
                });

            modelBuilder.Entity("WildBunch.Persistence.GameSessions.GameSessionDiaryDayEntity", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("SessionId", "Sequence");

                    b.ToTable("GameSessionTravelDiaryDays", (string)null);
                });

            modelBuilder.Entity("WildBunch.Persistence.GameSessions.GameSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("TravelDifficulty")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GameSessions", (string)null);
                });

            modelBuilder.Entity("WildBunch.Persistence.GameSessions.GameSessionLogEntryEntity", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Day")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Turn")
                        .HasColumnType("INTEGER");

                    b.HasKey("SessionId", "Sequence");

                    b.ToTable("GameSessionLogEntries", (string)null);
                });

            modelBuilder.Entity("WildBunch.Persistence.GameSessions.GameSessionComponentEntity", b =>
                {
                    b.HasOne("WildBunch.Persistence.GameSessions.GameSessionEntity", "Session")
                        .WithMany("Components")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("WildBunch.Persistence.GameSessions.GameSessionDiaryDayEntity", b =>
                {
                    b.HasOne("WildBunch.Persistence.GameSessions.GameSessionEntity", "Session")
                        .WithMany("TravelDiaryDays")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("WildBunch.Persistence.GameSessions.GameSessionLogEntryEntity", b =>
                {
                    b.HasOne("WildBunch.Persistence.GameSessions.GameSessionEntity", "Session")
                        .WithMany("LogEntries")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("WildBunch.Persistence.GameSessions.GameSessionEntity", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("LogEntries");

                    b.Navigation("TravelDiaryDays");
                });
#pragma warning restore 612, 618
        }
    }
}
