// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WildBunch.Persistence;

#nullable disable

namespace WildBunch.Persistence.Migrations
{
    [DbContext(typeof(WildBunchDbContext))]
    partial class WildBunchDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WildBunch.Persistence.GameSessions.GameSessionComponentEntity", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ComponentName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("ComponentVersion")
                        .HasColumnType("integer");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SessionId", "ComponentName");

                    b.ToTable("GameSessionComponents", (string)null);
                });

            modelBuilder.Entity("WildBunch.Persistence.GameSessions.GameSessionDiaryDayEntity", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SessionId", "Sequence");

                    b.ToTable("GameSessionTravelDiaryDays", (string)null);
                });

            modelBuilder.Entity("WildBunch.Persistence.GameSessions.GameSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GameDifficulty")
                        .HasColumnType("integer");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer");

                    b.Property<string>("SeedCode")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<long?>("SnapshotVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long>("StreamVersion")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("GameSessions", (string)null);
                });

            modelBuilder.Entity("WildBunch.Persistence.GameSessions.StoredEventEntity", b =>
                {
                    b.Property<Guid>("StreamId")
                        .HasColumnType("uuid");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("CausationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer");

                    b.HasKey("StreamId", "Sequence");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("StreamId", "Sequence")
                        .IsUnique();

                    b.ToTable("GameSessionStoredEvents", (string)null);
                });

            modelBuilder.Entity("WildBunch.Persistence.GameSessions.GameSessionComponentEntity", b =>
                {
                    b.HasOne("WildBunch.Persistence.GameSessions.GameSessionEntity", "Session")
                        .WithMany("Components")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("WildBunch.Persistence.GameSessions.GameSessionDiaryDayEntity", b =>
                {
                    b.HasOne("WildBunch.Persistence.GameSessions.GameSessionEntity", "Session")
                        .WithMany("TravelDiaryDays")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("WildBunch.Persistence.GameSessions.StoredEventEntity", b =>
                {
                    b.HasOne("WildBunch.Persistence.GameSessions.GameSessionEntity", "Session")
                        .WithMany("StoredEvents")
                        .HasForeignKey("StreamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("WildBunch.Persistence.GameSessions.GameSessionEntity", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("StoredEvents");

                    b.Navigation("TravelDiaryDays");
                });
#pragma warning restore 612, 618
        }
    }
}
