#!/usr/bin/env python3
"""Generate or validate the repo-wide INDEX.md mesh for wild-bunch."""

from __future__ import annotations

import argparse
import os
import re
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
EXCLUDED_DIR_NAMES = {".git", "__pycache__", "bin", "obj", "node_modules", ".local", "sdd", "dist", "TestResults", "output", "marketplace-source", ".codex", ".playwright-mcp", ".superpowers", ".pytest_cache"}
EXCLUDED_ROOT_NAMES = {".git", "__pycache__", "bin", "obj", "node_modules", ".local", "sdd", "dist", "TestResults", "output", "marketplace-source", ".codex", ".playwright-mcp", ".superpowers", ".pytest_cache"}
EXCLUDED_FILE_NAMES = {".git"}


@dataclass(frozen=True)
class IndexTarget:
    path: Path
    lines: list[str]


LINK_PATTERN = re.compile(r"\[([^\]]+)\]\(([^)]+)\)")

ADR_DIR_REL = Path("docs/adr")
ADR_STATUS_RE = re.compile(r"^## Status\s*\n\s*(.+?)\s*$", re.MULTILINE)
ADR_DATED_HISTORY_RE = re.compile(r"^## Dated Status History\s*\n(.*?)(?=^## |\Z)", re.MULTILINE | re.DOTALL)
ADR_DATE_RE = re.compile(r"(\d{4}-\d{2}-\d{2})")


def is_skill_root(path: Path) -> bool:
    return (path / "SKILL.md").exists() or (path / "overlay.yaml").exists()


def is_under(path: Path, ancestor: Path) -> bool:
    return path == ancestor or ancestor in path.parents


def should_descend(child: Path) -> bool:
    return child.name not in EXCLUDED_DIR_NAMES and not is_skill_root(child)


def should_index(path: Path) -> bool:
    if path == ROOT:
        return True
    relative = path.relative_to(ROOT)
    if any(part in EXCLUDED_ROOT_NAMES for part in relative.parts):
        return False
    return not is_skill_root(path)


def rel_link(current: Path, target: Path, label: str | None = None) -> str:
    rel = os.path.relpath(target, start=current).replace(os.sep, "/")
    return f"[{label or target.name}]({rel})"


def dir_link(current: Path, child: Path) -> str | None:
    skill_md = child / "SKILL.md"
    if skill_md.exists():
        rel = os.path.relpath(skill_md, start=current).replace(os.sep, "/")
        return f"[{child.name}]({rel})"
    if should_index(child):
        index_md = child / "INDEX.md"
        rel = os.path.relpath(index_md, start=current).replace(os.sep, "/")
        return f"[{child.name}]({rel})"
    rel = os.path.relpath(child, start=current).replace(os.sep, "/")
    return f"[{child.name}]({rel}/)"


def render_index(path: Path) -> str:
    dirs = []
    files = []
    for entry in sorted(path.iterdir(), key=lambda p: (not p.is_dir(), p.name.casefold(), p.name)):
        if entry.name == "INDEX.md":
            continue
        if entry.is_dir():
            if entry.name in EXCLUDED_DIR_NAMES:
                continue
            if is_skill_root(path):
                continue
            dirs.append(entry)
        else:
            if entry.name in EXCLUDED_FILE_NAMES:
                continue
            files.append(entry)

    lines: list[str] = ["# INDEX.md", ""]
    lines.append("This index is generated by `scripts/generate_index_mesh.py`.")
    lines.append("")

    if dirs:
        lines.append("## Directories")
        for child in dirs:
            link = dir_link(path, child)
            if link is not None:
                lines.append(f"- {link}")
        lines.append("")

    if files:
        lines.append("## Files")
        for child in files:
            lines.append(f"- {rel_link(path, child)}")
        lines.append("")

    if not dirs and not files:
        lines.append("No child entries.")
        lines.append("")

    rel_to_root = path.relative_to(ROOT)
    if rel_to_root == ADR_DIR_REL:
        lines.extend(render_adr_freshness_table(path))

    return "\n".join(lines).rstrip() + "\n"


def render_adr_freshness_table(adr_dir: Path) -> list[str]:
    """Render a per-ADR freshness table for the docs/adr INDEX.md.

    Parses each ADR file for its Status and the most recent date in the
    Dated Status History section. The "Last checked" column reflects the
    most recent dated entry — workers update it by adding a dated status
    history entry when they verify freshness.
    """
    adr_files = sorted(
        (f for f in adr_dir.iterdir() if f.is_file() and f.name.startswith("ADR-") and f.suffix == ".md"),
        key=lambda f: f.name,
    )
    if not adr_files:
        return []

    lines: list[str] = ["## ADR Freshness Table", ""]
    lines.append("| ADR | Status | Last checked |")
    lines.append("| --- | --- | --- |")
    for adr_file in adr_files:
        text = adr_file.read_text(encoding="utf-8")
        status_match = ADR_STATUS_RE.search(text)
        status = status_match.group(1).strip() if status_match else "unknown"
        last_checked = "unknown"
        history_match = ADR_DATED_HISTORY_RE.search(text)
        if history_match:
            dates = ADR_DATE_RE.findall(history_match.group(1))
            if dates:
                last_checked = max(dates)
        lines.append(f"| [{adr_file.name}]({adr_file.name}) | {status} | {last_checked} |")
    lines.append("")
    return lines


def normalize_text(text: str) -> str:
    return text.replace("\r\n", "\n").replace("\r", "\n")


def resolve_link_target(current: Path, target: str) -> Path | None:
    if target.startswith(("http://", "https://", "mailto:")):
        return None
    clean_target = target.split("#", 1)[0]
    if not clean_target:
        return None
    resolved = (current.parent / clean_target).resolve()
    if not is_under(resolved, ROOT):
        return None
    if target.endswith("/"):
        if resolved.is_dir():
            return resolved
        return None
    if resolved.exists():
        return resolved
    return None


def validate_rendered_links(path: Path, rendered: str) -> list[str]:
    failures: list[str] = []
    for label, raw_target in LINK_PATTERN.findall(rendered):
        resolved = resolve_link_target(path, raw_target)
        if resolved is None:
            continue
        if raw_target.endswith("/"):
            if not resolved.is_dir():
                failures.append(f"broken-link: {path.relative_to(ROOT)} -> {raw_target}")
            continue
        if not resolved.exists():
            failures.append(f"broken-link: {path.relative_to(ROOT)} -> {raw_target}")
    return failures


def walk_index_targets() -> list[IndexTarget]:
    targets: list[IndexTarget] = []
    for dirpath, dirnames, _filenames in os.walk(ROOT):
        current = Path(dirpath)
        dirnames[:] = sorted(
            (name for name in dirnames if should_descend(current / name)),
            key=lambda name: (name.casefold(), name),
        )
        if should_index(current):
            targets.append(IndexTarget(path=current / "INDEX.md", lines=render_index(current).splitlines()))
    return targets


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate or validate the repo-wide INDEX.md mesh")
    parser.add_argument("--check", "--validate", dest="check", action="store_true", help="validate without writing")
    args = parser.parse_args()

    targets = walk_index_targets()
    expected_paths = {target.path for target in targets}
    actual_paths = {
        path
        for path in ROOT.rglob("*")
        if path.is_file() and path.name == "INDEX.md" and not any(part in EXCLUDED_ROOT_NAMES for part in path.relative_to(ROOT).parts)
    }
    unexpected = sorted(path for path in actual_paths if path not in expected_paths)
    missing = sorted(path for path in expected_paths if path not in actual_paths)

    if args.check:
        mismatches: list[str] = []
        for target in targets:
            if not target.path.exists():
                mismatches.append(f"missing: {target.path.relative_to(ROOT)}")
                continue
            current = normalize_text(target.path.read_text(encoding="utf-8"))
            rendered = "\n".join(target.lines).rstrip() + "\n"
            if current != rendered:
                mismatches.append(f"stale: {target.path.relative_to(ROOT)}")
            mismatches.extend(validate_rendered_links(target.path, rendered))
        if unexpected:
            mismatches.extend(f"unexpected: {path.relative_to(ROOT)}" for path in unexpected)
        if missing:
            mismatches.extend(f"missing: {path.relative_to(ROOT)}" for path in missing)
        if mismatches:
            raise ValueError("INDEX mesh is stale or inconsistent:\n" + "\n".join(mismatches))
        print(f"OK index mesh: {len(targets)} indexes current")
        return 0

    written = 0
    for target in targets:
        rendered = "\n".join(target.lines).rstrip() + "\n"
        target.path.parent.mkdir(parents=True, exist_ok=True)
        with target.path.open("w", encoding="utf-8", newline="\n") as handle:
            handle.write(rendered)
        written += 1

    obsolete = sorted(path for path in actual_paths if path not in expected_paths)
    for path in obsolete:
        path.unlink()
    link_failures: list[str] = []
    for target in targets:
        rendered = "\n".join(target.lines).rstrip() + "\n"
        link_failures.extend(validate_rendered_links(target.path, rendered))
    if link_failures:
        raise ValueError("INDEX mesh produced broken links:\n" + "\n".join(link_failures))
    print(f"Wrote index mesh: {written} files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
